Fix intersection(Point_2,Point_2)
It seems it was never tested, and never worked.

PR #2792 introduced a compilation error in cgal-swig-bindings, by the
addition of `do_intersect(Point_2,Circle_2)` and
`intersection(Point_2,Circle_2)`:

> /usr/include/CGAL/Kernel/function_objects.h:2954:63: error: call of overloaded ‘do_intersect(const CGAL::Point_2<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >&, const CGAL::Point_2<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >&, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >)’ is ambiguous
>     { return Intersections::internal::do_intersect(t1, t2, K()); }
>                                                               ^

https://travis-ci.org/CGAL/cgal-swig-bindings/jobs/509442278#L4727