Attempt to fix the compilation issue with MSCV 2012 and Boost 1.53
```
[ 50%] Building CXX object CMakeFiles/mesh_implicit_sphere_variable_size.dir/mesh_implicit_sphere_variable_size.cpp.obj
	C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  @C:\Users\afabri\AppData\Local\Temp\nmCD61.tmp
mesh_implicit_sphere_variable_size.cpp
C:\3rdPartyLibs\boost_1_53_0\boost/type_traits/remove_cv.hpp(37) : error C2039: 'unqualified_type' : is not a member of 'boost::detail::cv_traits_imp<T>'
        with
        [
            T=double (__cdecl *const *)(const Point &)
        ]
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-23/Mesh_3_Examples/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-64bits.gz

Maybe passing a function pointer instead of a function lvalue will fix the
compilation error.